import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
import Link from "next/link";
import { LoginIcon, LogoutIcon } from "./_components/icons";
import { auth, isLoggedIn, signOut } from "./_lib/auth";
import { unstable_noStore as noStore } from "next/cache";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "h-screen bg-slate-100 text-slate-900"
        )}
      >
        <div className="h-full flex flex-col min-h-0">
          <div className="bg-slate-900 border-b border-slate-800 flex items-center justify-between py-4 px-8 box-border">
            <Link href="/home" className="block leading-3 w-1/3">
              <div className="font-black text-2xl text-white">Trexno</div>
              <div className="text-slate-500">a Next.js Demo</div>
            </Link>

            <div className="w-1/3 flex justify-end">
              <LoginOrOutButton />
            </div>
          </div>

          <div className="flex-grow min-h-0 h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}

async function logoutAction() {
  "use server";
  await signOut();
}

async function LoginOrOutButton() {
  noStore();

  return (await isLoggedIn()) ? (
    <form action={logoutAction}>
      <button className="block text-center">
        <LogoutIcon />
        <br />
        <span className="text-slate-500 text-xs uppercase font-bold">
          Log out
        </span>
      </button>
    </form>
  ) : (
    <Link href="/login" className="block text-center">
      <LoginIcon />
      <br />
      <span className="text-slate-500 text-xs uppercase font-bold">Log in</span>
    </Link>
  );
}
